version: "3.2"


services:
  db:
    image: postgres:10
    ports:
      - "5342:5342"
    networks:
      internal-network:
        aliases:
          - localdb
    volumes:
      - /data/pgsql/10/data:/var/lib/pgsql/10/data
    environment:
      - PGDATA=/var/lib/pgsql/10/data
      - PGUSER=postgres

  sregistry:
    build: .
    image: sregistry:latest
    restart: always
    ports:
      - "3032:3032"
    depends_on:
      - db
    networks:
      internal-network:
        aliases:
          - localuwsgi
    volumes:
      - /data/sregistry:/data/sregistry
    links:
      - "db:localdb"

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - sregistry
    networks:
      - internal-network
    volumes:
      - /data/sregistry/www:/var/www:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    links:
      - "sregistry:uwsgi"


networks:
  internal-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
